# Generated by Django 3.2.17 on 2023-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('question4', models.TextField()),
                ('question5', models.TextField()),
                ('question6', models.TextField()),
                ('question7', models.TextField()),
                ('question8', models.TextField()),
                ('question9', models.TextField()),
                ('question10', models.TextField()),
            ],
        ),
    ]
